// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RunController from "./run_controller.ts"
application.register("run", RunController)

import RunSummaryChartController from "./run_summary_chart_controller.js"
application.register("run-summary-chart", RunSummaryChartController)

import SummaryController from "./summary_controller.ts"
application.register("summary", SummaryController)
