// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RunController from "./run_controller.js"
application.register("run", RunController)

import SummaryController from "./summary_controller.js"
application.register("summary", SummaryController)
